# Generated by Django 2.2.6 on 2019-10-30 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistique', '0002_visitor_infoss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visiteur_infos',
            old_name='date_update',
            new_name='event_date',
        ),
        migrations.RemoveField(
            model_name='visiteur_infos',
            name='date_add',
        ),
    ]
