# Generated by Django 2.2.6 on 2019-10-30 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistique', '0005_visitor_infos_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visitor_Infos_user',
            new_name='Visitor_Infos',
        ),
        migrations.DeleteModel(
            name='Visiteur_Infos',
        ),
        migrations.DeleteModel(
            name='Visitor_Infoss',
        ),
    ]
