# Generated by Django 2.2.6 on 2019-10-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistique', '0007_visitor_infoss'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor_infoss',
            name='continent',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitor_infoss',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitor_infoss',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitor_infoss',
            name='pays',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitor_infoss',
            name='reseau_mobile',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitor_infoss',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='visitor_infoss',
            name='ville',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
