# Generated by Django 2.2.6 on 2019-10-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistique', '0008_auto_20191030_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor_Infose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('event_date', models.DateTimeField(auto_now=True)),
                ('pays', models.CharField(max_length=50)),
                ('ville', models.CharField(max_length=50)),
                ('continent', models.CharField(max_length=50)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('page_visited', models.TextField()),
                ('reseau_mobile', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
