# Generated by Django 2.2.6 on 2019-10-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191026_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='titre_slug',
            field=models.SlugField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
