# Generated by Django 2.2.6 on 2019-10-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191026_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag_name',
            field=models.ManyToManyField(related_name='tag_article', to='blog.Tag'),
        ),
    ]
