# Generated by Django 2.2.6 on 2019-10-27 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191026_2046'),
        ('blog', '0004_auto_20191027_1512'),
    ]

    operations = [
    ]
