# Generated by Django 2.2.6 on 2019-10-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_merge_20191027_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='coment',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='like',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
