# Generated by Django 2.2.6 on 2019-10-27 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191027_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='coment',
            new_name='nb_coment',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='like',
            new_name='nb_like',
        ),
    ]
