# Generated by Django 2.2.6 on 2019-10-27 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20191027_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='nb_coment',
        ),
        migrations.RemoveField(
            model_name='article',
            name='nb_like',
        ),
    ]
