# Generated by Django 2.2.6 on 2019-10-27 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_merge_20191027_1923'),
        ('blog', '0010_auto_20191027_2131'),
    ]

    operations = [
    ]
