# Generated by Django 2.2.6 on 2019-10-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_merge_20191027_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='titre_slug',
            field=models.SlugField(editable=False, max_length=255),
        ),
    ]
