# Generated by Django 2.2.6 on 2019-10-28 00:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20191027_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='titre_slug',
            field=models.SlugField(default=uuid.uuid4, editable=False, max_length=255),
        ),
    ]
