# Generated by Django 2.2.6 on 2019-10-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_serarch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serarch',
            options={'verbose_name': 'serarch', 'verbose_name_plural': 'les recherches des utilisateurs'},
        ),
        migrations.AddField(
            model_name='article',
            name='nb_com',
            field=models.IntegerField(default='0'),
        ),
    ]
