# Generated by Django 2.2.6 on 2019-10-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20191028_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_ago',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
