# Generated by Django 2.2.6 on 2019-10-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_article_date_ago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_ago',
            field=models.DateTimeField(),
        ),
    ]
