# Generated by Django 2.2.6 on 2019-10-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20191028_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_ago',
            field=models.CharField(default='0', editable=False, max_length=250),
        ),
    ]
