# Generated by Django 2.2.6 on 2019-10-29 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_remove_article_date_ago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctegorieuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
