# Generated by Django 2.2.6 on 2019-10-30 18:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20191029_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='temps_de_lecture',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='titre_slug',
            field=models.SlugField(default=uuid.uuid4, editable=False, max_length=255, null=True),
        ),
    ]
