# Generated by Django 2.2.6 on 2019-10-30 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20191030_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='nom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
