# Generated by Django 2.2.6 on 2019-10-31 00:41

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20191030_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='contenu',
            field=tinymce.models.HTMLField(null=True, verbose_name='article_description'),
        ),
    ]
