# Generated by Django 2.2.6 on 2019-10-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_auto_20191027_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='imageprofile',
            field=models.ImageField(default='profileimage.png', upload_to='Profile_Image'),
        ),
    ]
